# Generated by Django 5.0.4 on 2024-05-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='margen',
            field=models.FloatField(default=0.3),
        ),
    ]
