# Generated by Django 5.0.4 on 2024-05-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_is_precio_standar_categoria_precio_standar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriaproducto',
            unique_together={('categoria', 'producto')},
        ),
    ]
