# Generated by Django 5.0.4 on 2024-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_promocion_promocionproducto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocionproducto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
    ]
