# Generated by Django 5.0.4 on 2024-05-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_promocionproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
    ]
