# Generated by Django 5.0.4 on 2024-05-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_rename_viandafecha_agendafecha'),
        ('productos', '0008_alter_promocion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vianda',
            fields=[
                ('vianda_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viandas', to='agendas.agenda')),
            ],
            options={
                'verbose_name': 'Vianda',
                'verbose_name_plural': 'Viandas',
                'unique_together': {('nombre', 'agenda')},
            },
        ),
        migrations.CreateModel(
            name='ViandaProducto',
            fields=[
                ('vianda_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viandas', to='productos.producto')),
                ('vianda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.vianda')),
            ],
            options={
                'unique_together': {('vianda', 'producto')},
            },
        ),
    ]
