# Generated by Django 5.0.4 on 2024-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_vianda_viandaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vianda',
            name='precio_standar',
            field=models.FloatField(default=0),
        ),
    ]
