# Generated by Django 5.0.4 on 2024-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_vianda_precio_standar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='precio_standar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='productoinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vianda',
            name='precio_standar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
