# Generated by Django 5.0.4 on 2024-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_domicilio_remove_empleado_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
    ]
