# Generated by Django 5.0.4 on 2024-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleado_cargo_remove_empleado_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default='2024-05-04'),
            preserve_default=False,
        ),
    ]
