# Generated by Django 5.0.4 on 2024-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='aportes',
            field=models.DecimalField(decimal_places=2, default=18.9, max_digits=10),
            preserve_default=False,
        ),
    ]
