# Generated by Django 5.0.4 on 2024-05-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_categoria_aportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.categoria'),
        ),
    ]
