# Generated by Django 5.0.4 on 2024-05-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleadocategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empleados.categoria'),
        ),
    ]
