# Generated by Django 5.0.4 on 2024-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_empleadocategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='aportes',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=10),
        ),
    ]
