# Generated by Django 5.0.4 on 2024-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctipo',
            name='sigla',
            field=models.CharField(default='DNI', max_length=5),
        ),
    ]
