# Generated by Django 5.0.4 on 2024-05-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0006_alter_personadomicilio_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='personas.persona')),
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
            bases=('personas.persona',),
        ),
    ]
