# Generated by Django 5.0.4 on 2024-05-10 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.persona')),
                ('cuenta_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=('personas.persona',),
        ),
        migrations.CreateModel(
            name='ClienteVianda',
            fields=[
                ('cliente_vianda_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viandas', to='clientes.cliente')),
                ('vianda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='productos.vianda')),
            ],
            options={
                'verbose_name': 'Cliente Vianda',
                'verbose_name_plural': 'Clientes Viandas',
                'ordering': ['cliente__nombre', 'vianda__nombre'],
            },
        ),
    ]
