# Generated by Django 5.0.4 on 2024-05-07 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0012_alter_productoinsumo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVianda',
            fields=[
                ('cliente_vianda_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viandas', to='clientes.cliente')),
                ('vianda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='productos.vianda')),
            ],
            options={
                'verbose_name': 'Cliente Vianda',
                'verbose_name_plural': 'Clientes Viandas',
                'ordering': ['cliente__nombre', 'vianda__nombre'],
            },
        ),
    ]
