# Generated by Django 5.0.4 on 2024-05-10 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unidad_media', models.CharField(choices=[('uni', 'unidad'), ('kg', 'kilogramos'), ('l', 'litros')], max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notificar', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='insumos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoProveedor',
            fields=[
                ('insumo_proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('predeterminado', models.BooleanField(default=False)),
                ('notificado', models.BooleanField(default=False)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='insumos.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='proveedores.proveedor')),
            ],
            options={
                'unique_together': {('insumo', 'proveedor')},
            },
        ),
    ]
