# Generated by Django 5.0.4 on 2024-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('unidad_media', models.CharField(choices=[('uni', 'unidad'), ('kg', 'kilogramos'), ('l', 'litros')], max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
            ],
        ),
    ]
