# Generated by Django 5.0.4 on 2024-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
