# Generated by Django 5.0.4 on 2024-05-04 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_alter_insumo_marca'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoProveedor',
            fields=[
                ('insumo_proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='insumos.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_upd', models.DateField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='insumos.insumo')),
            ],
        ),
    ]
