# Generated by Django 5.0.4 on 2024-05-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_insumoproveedor_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='minimo',
            field=models.FloatField(default=0),
        ),
    ]
