# Generated by Django 5.0.4 on 2024-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='notificar',
            field=models.BooleanField(default=False),
        ),
    ]
