# Generated by Django 5.0.4 on 2024-05-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_stock_notificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoproveedor',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumoproveedor',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
