# Generated by Django 5.0.4 on 2024-05-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_insumoproveedor_mensaje_and_more'),
        ('proveedores', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insumoproveedor',
            unique_together={('insumo', 'proveedor')},
        ),
    ]
