# Generated by Django 5.0.4 on 2024-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_alter_insumoproveedor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
