# Generated by Django 5.0.4 on 2024-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_stock_notificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='notificado',
        ),
        migrations.AddField(
            model_name='insumoproveedor',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
