# Generated by Django 5.0.4 on 2024-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0010_remove_stock_notificado_insumoproveedor_notificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
