# Generated by Django 5.0.4 on 2024-05-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
