# Generated by Django 5.0.4 on 2024-05-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
    ]
