# Generated by Django 5.0.4 on 2024-05-07 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_personadomicilio_direccion_and_more'),
        ('proveedores', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='persona_ptr',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='personas.persona'),
            preserve_default=False,
        ),
    ]
