# Generated by Django 5.0.4 on 2024-05-07 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_personadomicilio_direccion_and_more'),
        ('proveedores', '0004_remove_proveedor_persona_ptr_proveedor_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='persona',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona_ptr',
            field=models.OneToOneField(auto_created=True, default=11, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='personas.persona'),
            preserve_default=False,
        ),
    ]
