# Generated by Django 5.0.4 on 2024-05-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_personadomicilio_direccion_and_more'),
        ('proveedores', '0005_remove_proveedor_persona_proveedor_persona_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_id',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='persona_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.persona'),
        ),
    ]
