# Generated by Django 5.0.4 on 2024-05-05 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViandaFecha',
            fields=[
                ('vianda_fechas_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='agendas.agenda')),
            ],
        ),
    ]
