# Generated by Django 5.0.4 on 2024-05-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_viandafecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViandaFecha',
            new_name='AgendaFecha',
        ),
    ]
