# Generated by Django 5.0.4 on 2024-05-10 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_upd', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.persona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaDet',
            fields=[
                ('venta_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Venta'), (2, 'Promocion'), (3, 'Vianda')], default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_upd', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.producto')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_promocion', to='productos.promocion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
                ('vianda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_vianda', to='productos.vianda')),
            ],
            options={
                'unique_together': {('venta', 'producto', 'promocion', 'vianda')},
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
        migrations.CreateModel(
            name='VentaPromocion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
        migrations.CreateModel(
            name='VentaVianda',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
    ]
