# Generated by Django 5.0.4 on 2024-05-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_promocionproducto_unique_together_and_more'),
        ('ventas', '0002_venta_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.producto'),
        ),
    ]
