# Generated by Django 5.0.4 on 2024-07-02 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ventadet_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
