# Generated by Django 5.0.4 on 2024-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_user_alter_venta_fecha_alter_venta_fecha_upd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadet',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='fecha_upd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
