# Generated by Django 5.0.4 on 2024-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_ventadet_fecha_alter_ventadet_fecha_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadet',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Venta'), (2, 'Promocion')], default=1),
        ),
    ]
