# Generated by Django 5.0.4 on 2024-05-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_promocion_options'),
        ('ventas', '0006_ventadet_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadet',
            name='promocion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.promocion'),
            preserve_default=False,
        ),
    ]
