# Generated by Django 5.0.4 on 2024-05-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_promocion_options'),
        ('ventas', '0007_ventadet_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadet',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.promocion'),
        ),
    ]
