# Generated by Django 5.0.4 on 2024-05-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_ventadet_promocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadet',
            name='promocion',
        ),
    ]
