# Generated by Django 5.0.4 on 2024-05-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_promocion_options'),
        ('ventas', '0009_remove_ventadet_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadet',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.promocion'),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.producto'),
        ),
    ]
