# Generated by Django 5.0.4 on 2024-05-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_promocion_options'),
        ('ventas', '0010_ventadet_promocion_alter_ventadet_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
        migrations.CreateModel(
            name='VentaPromocion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='promocion',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_promocion', to='productos.promocion'),
        ),
    ]
