# Generated by Django 5.0.4 on 2024-05-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_vianda_viandaproducto'),
        ('ventas', '0011_ventaproducto_ventapromocion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaVianda',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.ventadet',),
        ),
        migrations.AddField(
            model_name='ventadet',
            name='vianda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_vianda', to='productos.vianda'),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_promocion', to='productos.promocion'),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Venta'), (2, 'Promocion'), (3, 'Vianda')], default=1),
        ),
    ]
