# Generated by Django 5.0.4 on 2024-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_ventavianda_ventadet_vianda_alter_ventadet_promocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ventadet',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
