# Generated by Django 5.0.4 on 2024-05-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_categoria_precio_standar_alter_producto_margen_and_more'),
        ('ventas', '0013_alter_venta_total_alter_ventadet_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ventadet',
            unique_together={('venta', 'producto', 'promocion', 'vianda')},
        ),
    ]
