# Generated by Django 5.0.4 on 2024-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_ventadet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadet',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
