# Generated by Django 5.0.4 on 2024-05-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.doctipo'),
        ),
        migrations.DeleteModel(
            name='DocTipo',
        ),
    ]
