# Generated by Django 5.0.4 on 2024-05-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_tipo_doc_delete_doctipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nacimiento',
            new_name='fec_nac',
        ),
    ]
