# Generated by Django 5.0.4 on 2024-05-04 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_rename_apellidos_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadomicilio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personaemail',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personatelefono',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='personas.persona'),
        ),
    ]
