# Generated by Django 5.0.4 on 2024-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_persona_apellido_alter_persona_fec_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadomicilio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaemail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personatelefono',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
